### PR TITLE
Use stubs from Opal GEMs when MRI requires/Rail/Bundler is used

### PR DESCRIPTION
**Pull request by wied03**
Also try and make Bundler detection more reliable with RUBYOPT

### CODE REVIEW

**Comment by wied03** [comment]
Implements https://github.com/cj/opal-webpack/issues/24 - @cj  - want to have a look?

**Comment by cj** [comment]
@wied03 not to sure about this `webpack is run with the RAILS_ENV environment variable set` all our apps and people that don't use rails use `RACK_ENV`.

**Comment by wied03** [comment]
@cj - That's not new with this PR. Logic was already there for that and was moved from getLoadPaths and it only kicks in if RAILS_ENV is set (which is not mandatory of course).

**Comment by wied03** [comment]
@cj - Also, if someone is using RACK_ENV, there is no special behavior needed by the loader here. The loader only uses RAILS_ENV as a way to see if someone is using Rails and get asset paths from Sprockets (e.g. app/assets/javascripts, not just Opal).

If someone had a Rack based app like Sinatra, they would still get the benefit of Bundler integration by running all of this with `bundle`, in which case the `else` in the code below would fire:
```js
if (useBundler) {
    if (env.RAILS_ENV) {
      // using rails runner to try and take advantage of spring
      return bundlerExecute(`rails runner "${rubyCode}"`)
    }
    else {
      return bundlerExecute(`ruby -e "Bundler.require; ${rubyCode}"`)
    }
  }
```

**Comment by wied03** [comment]
The only thing that's missing related to this that I know of is Sprockets based paths for someone not using Rails. In that case, like Sinatra, this would only fetch load paths that GEMs have added using `Opal.append_path`. I can't imagine many people would use Sprockets but not Rails.

As discussed above though, this isn't new with this PR.

**Comment by cj** [comment]
Yes, this makes perfect sense.  Feel free to update the package.json version and merge it in.

**Pull request merged**
